/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
<<<<<<< HEAD
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
=======
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"]
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import("element-plus/es")["ElInput"]
>>>>>>> a8ac1d01a77576182e7b613954d3b5b260be1dc2
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ELTABLE: typeof import("element-plus/es")["ElTable"]
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
<<<<<<< HEAD
    ElTag: typeof import('element-plus/es')['ElTag']
=======
    ElTag: typeof import("element-plus/es")["ElTag"]
>>>>>>> a8ac1d01a77576182e7b613954d3b5b260be1dc2
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
